AWSTemplateFormatVersion: 2010-09-09
Description: "AWS DevOps Springboard - Landing Zone Pipeline"
Metadata:
    Stack: 3
    VersionDate: 2017-07-26
    Input:
      Description: "AWS Codepipeline for Cloudformation Stack Continuous Delivery"
    "AWS::CloudFormation::Interface":
        ParameterGroups:
          - Label:
              default: "CodePipeline Configuration"
            Parameters:
              - TemplatesBucket
              - StackPrefix
              - NotifyEmail
          - Label:
              default: "Repository Details"
            Parameters:
              - GitUser
              - GitRepo
              - GitBranch

Parameters:
  TemplatesBucket:
    Description: S3 bucket to which nested CF templates are synced
    Type: String
  StackPrefix:
    Description: Stack Prefix
    Type: String
    MaxLength: 32
    AllowedPattern: '[a-z0-9\-]+'
    Default: "devops-springboard"
  GitUser:
    Description: 'User/Owner for Git repo'
    Type: String
  GitRepo:
    Description: 'Git repository name'
    Type: 'String'
  GitBranch:
    Description: 'Git Branch being deployed'
    Type: 'String'
  #Uncomment below lines to add notification to the pipeline
  #NotifyEmail:
  #  Type: String
  #  Description: Email for  Landing Zone  administrators


Resources:
  CFNRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [cloudformation.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: !Sub ${StackPrefix}-network-CF
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - '*'
                Effect: Allow
                Resource: '*'

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codepipeline.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: !Sub ${StackPrefix}-Pipeline-Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 's3:*'
                - 'codebuild:*'
                - 'cloudformation:CreateStack'
                - 'cloudformation:DescribeStacks'
                - 'cloudformation:DeleteStack'
                - 'cloudformation:UpdateStack'
                - 'cloudformation:CreateChangeSet'
                - 'cloudformation:ExecuteChangeSet'
                - 'cloudformation:DeleteChangeSet'
                - 'cloudformation:DescribeChangeSet'
                - 'cloudformation:SetStackPolicy'
                - 'iam:PassRole'
                - 'sns:Publish'
                - 'codecommit:BatchGetRepositories'
                - 'codecommit:Get*'
                - 'codecommit:GitPull'
                - 'codecommit:List*'
                - 'codecommit:Update*'
                - 'codecommit:Test*'
                - 'codecommit:UploadArchive'
                Effect: Allow
                Resource: '*'

  #Uncomment below lines to add notification to the pipeline
  #PipelineSNSTopic:
  #  Type: AWS::SNS::Topic
  #  Properties:
  #    DisplayName: "Landing Zone Notifications"
  #    Subscription:
  #      - Endpoint: !Ref NotifyEmail
  #        Protocol: email

  #PiplineCloudwatchRule:
  #  Type: AWS::Events::Rule
  #  Properties:
  #    Description: "Cloudwatch events rule to detect pipeline failures"
  #    State: "ENABLED"
  #    EventPattern:
  #      source:
  #      - "aws.codepipeline"
  #      detail-type:
  #      - "CodePipeline Stage Execution State Change"
  #      detail:
  #        state:
  #          - "STARTED"
  #        pipeline:
  #          - !Ref Pipeline
  #        stage:
  #          - IAMStackDeploy

  #    Targets:
  #    - Arn: !Ref PipelineSNSTopic
  #      Id: PipelineNoticationSNS
  #      InputTransformer:
  #        InputPathsMap:
  #          pipeline: $.detail.pipeline
  #        InputTemplate: !Sub '"The Pipeline <pipeline> has started to deploy IAM stack."'
  #  DependsOn: PipelineSNSTopicPolicy

  #PipelineSNSTopicPolicy:
  #  Type: AWS::SNS::TopicPolicy
  #  Properties:
  #    PolicyDocument:
  #      Id: MyTopicPolicy
  #      Version: '2012-10-17'
  #      Statement:
  #      - Sid: TrustCWEToPublishEventsToMyTopic
  #        Effect: Allow
  #        Principal:
  #          Service: "events.amazonaws.com"
  #        Action: sns:Publish
  #        Resource: !Ref PipelineSNSTopic
  #    Topics:
  #    - !Ref PipelineSNSTopic

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        #EncryptionKey: !Ref KMSKeyId
        Location: !Ref TemplatesBucket
        Type: S3
      DisableInboundStageTransitions: []
      RestartExecutionOnUpdate: true
      Name: !Sub "${StackPrefix}-lz-pipeline"
      RoleArn: !GetAtt PipelineRole.Arn
      Stages:
        - Name: FetchFromGit
          Actions:
            - Name: TemplateSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: '1'
              Configuration:
                S3Bucket: !Ref TemplatesBucket
                S3ObjectKey: !Sub ${GitUser}/${GitRepo}/branch/${GitBranch}/${GitUser}_${GitRepo}_branch_${GitBranch}.zip
                PollForSourceChanges: true
              OutputArtifacts:
                - Name: S3Artifact
              RunOrder: '1'
        - Name: IAMStackDeploy
          Actions:
            - Name: IAMCreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: S3Artifact
              Configuration:
                Capabilities: CAPABILITY_NAMED_IAM
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !GetAtt CFNRole.Arn
                StackName: !Sub ${StackPrefix}-iam
                ChangeSetName: !Sub ${StackPrefix}-iam-changeset
                TemplateConfiguration:  "S3Artifact::cf-templates/iam/config_params.json"
                TemplatePath: "S3Artifact::cf-templates/iam/iam.yml"
                ParameterOverrides:
                    !Sub |
                      {
                        "StackPrefix": "${StackPrefix}"
                      }
              RunOrder: '1'
            - Name: IAMExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                Capabilities: CAPABILITY_NAMED_IAM
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: !Sub ${StackPrefix}-iam-changeset
                RoleArn: !GetAtt CFNRole.Arn
                StackName: !Sub ${StackPrefix}-iam
              RunOrder: '3'
        - Name: NetworkStackDeploy
          Actions:
            - Name: NetworkCreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: S3Artifact
              Configuration:
                Capabilities: CAPABILITY_NAMED_IAM
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !GetAtt CFNRole.Arn
                StackName: !Sub ${StackPrefix}-network
                ChangeSetName: !Sub ${StackPrefix}-network-changeset
                TemplateConfiguration:  "S3Artifact::cf-templates/network/config_params.json"
                TemplatePath: "S3Artifact::cf-templates/network/network.yml"
                ParameterOverrides:
                     !Sub |
                       {
                          "StackPrefix": "${StackPrefix}"
                       }
              RunOrder: '1'
            - Name: NetworkExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                Capabilities: CAPABILITY_NAMED_IAM
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: !Sub ${StackPrefix}-network-changeset
                RoleArn: !GetAtt CFNRole.Arn
                StackName: !Sub ${StackPrefix}-network
              RunOrder: '3'
        - Name: ECSStackDeploy
          Actions:
            - Name: CreateChangeSetECSCluster
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: S3Artifact
              Configuration:
                Capabilities: CAPABILITY_NAMED_IAM
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !GetAtt CFNRole.Arn
                StackName: !Sub ${StackPrefix}-cluster
                ChangeSetName: !Sub ${StackPrefix}-cluster-changeset
                TemplateConfiguration:  "S3Artifact::cf-templates/ecs-cluster/config_params.json"
                TemplatePath: "S3Artifact::cf-templates/ecs-cluster/ecs.yml"
                ParameterOverrides:
                    !Sub |
                      {
                        "StackPrefix": "${StackPrefix}"
                      }
              RunOrder: '1'
            - Name: ExecuteChangeSetEcsCluster
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                Capabilities: CAPABILITY_NAMED_IAM
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: !Sub ${StackPrefix}-cluster-changeset
                RoleArn: !GetAtt CFNRole.Arn
                StackName: !Sub ${StackPrefix}-cluster
              RunOrder: '3'
        - Name: AnchoreDBStackDeploy
          Actions:
            - Name: CreateChangeSetAnchoreDB
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: S3Artifact
              Configuration:
                Capabilities: CAPABILITY_NAMED_IAM
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !GetAtt CFNRole.Arn
                StackName: !Sub ${StackPrefix}-anchore-db
                ChangeSetName: !Sub ${StackPrefix}-anchore-db-changeset
                TemplateConfiguration:  "S3Artifact::cf-templates/anchore-db/config_params.json"
                TemplatePath: "S3Artifact::cf-templates/anchore-db/anchore-db.yml"
                ParameterOverrides:
                    !Sub |
                      {
                        "StackPrefix": "${StackPrefix}"
                      }
              RunOrder: '1'
            - Name: ExecuteChangeSetAnchoreDB
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                Capabilities: CAPABILITY_NAMED_IAM
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: !Sub ${StackPrefix}-anchore-db-changeset
                RoleArn: !GetAtt CFNRole.Arn
                StackName: !Sub ${StackPrefix}-anchore-db
              RunOrder: '3'
        - Name: ServiceManagerStackDeploy
          Actions:
            - Name: ServiceManagerCreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: S3Artifact
              Configuration:
                Capabilities: CAPABILITY_NAMED_IAM
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !GetAtt CFNRole.Arn
                StackName: !Sub ${StackPrefix}-service-manager
                ChangeSetName: !Sub ${StackPrefix}-service-changeset
                TemplateConfiguration:  "S3Artifact::cf-templates/service-manager-pipeline/config_params.json"
                TemplatePath: "S3Artifact::cf-templates/service-manager-pipeline/service-manager.yml"
                ParameterOverrides:
                  !Sub |
                    {
                      "GitUser": "${GitUser}",
                      "ArtifactBucketName": "${TemplatesBucket}",
                      "PipelineIamRoleArn": "${PipelineRole.Arn}",
                      "StackPrefix": "${StackPrefix}"
                    }
              RunOrder: '1'
            - Name: ServiceManagerExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                Capabilities: CAPABILITY_NAMED_IAM
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: !Sub ${StackPrefix}-service-changeset
                RoleArn: !GetAtt CFNRole.Arn
                StackName: !Sub ${StackPrefix}-service-manager
              RunOrder: '3'

