---
AWSTemplateFormatVersion: 2010-09-09
Description: Template for deploying stack

Parameters:
  StackPrefix:
    Type: String
    Description: The StackPrefix for all LZ stacks
    Default: ecs-workshop

Resources:
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          -
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - ecs.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole

Outputs:
  ServiceRole:
    Value: !Ref ServiceRole
    Export:
      Name: !Sub ${StackPrefix}-service-role
  ServiceRoleArn:
    Value: !GetAtt ServiceRole.Arn
    Export:
      Name: !Sub ${StackPrefix}-service-role-arn
