---
AWSTemplateFormatVersion: 2010-09-09
Description: Template for deploying stack

Parameters:
  LZPrefix:
    Type: String
    Description: The LZ Prefix
    Default: ecs-workshop

Resources:
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam:aws:policy/service-role/AmazonEC2ConatinerServiceRole

Outputs:
  ServiceRole:
    Value: !Ref ServiceRole
    Export:
      Name: !Sub ${LZPrefix}-service-role
  ServiceRoleArn:
    Value: !GetAtt ServiceRole.Arn 
    Export:
      Name: !Sub ${LZPrefix}-service-role-arn
