---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for deploying ECS cluster'
# TODO:
# 1. Create ECS cluster
# 2. Create ALB
# 3. Launch seed service

Parameters:
  ClusterName:
    Type: String
    Description: The ECS Cluster name
  StackPrefix:
    Type: String
    Description: The Stack Prefix
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName
  serviceALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      SecurityGroupIngress:
        - ToPort: 80
          IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
      VpcId:
        Fn::ImportValue:
          !Sub ${StackPrefix}-VpcId
      GroupDescription: Service ALB SG

  ECSLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: 
      Subnets:
        - !ImportValue
            Fn::Sub: "${StackPrefix}-Public-Subnet-0"
        - !ImportValue
            Fn::Sub: "${StackPrefix}-Public-Subnet-1"
      #Target Groups
      SecurityGroups:
        !Ref serviceALBSG
      Scheme: internet-facing

