AWSTemplateFormatVersion: 2010-09-09
Description: AWS ECS Workshop - Network Stack
Metadata:
  VersionDate: 2017-07-24
  # Others

Parameters:
  StackPrefix:
    Type: String
    Description: Prefix used for naming the resources created. ${StackPrefix}-<resource>.
  ServiceBucketName:
    Type: String
    Description: Name for bucket we will use for our library
  ServiceBucketPath:
    Type: String
    Description: Path along the bucket where we'll put the templates
  ArtifactBucketName:
    Type: String
    Description: Name for bucket being used to read the artifacts
  PipelineIamRoleArn:
    Type: String
    Description: Arn of role to use for managing this pipeline
  GitHubUser:
    Description: 'User for GitHub'
    Type: String
  GitRepo:
    Description: 'Git repo name'
    Type: 'String'
  GitBranch:
    Description: 'Branch being deployed'
    Type: 'String'
  GitHubToken:
    Description: 'OAuth Token for repo access'
    Type: 'String'
    Default: ""

Resources:
  ServicesBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref ServiceBucketName
  BuildIamRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          -
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: 'codebuild.amazonaws.com'
      Policies:
        -
          PolicyName: SyncToTemplatesBucket
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action: s3:ListAllMyBuckets
                Resource: arn:aws:s3:::*
              -
                Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - !Sub arn:aws:s3:::${ServiceBucketName}/${ServiceBucketPath}/${GitRepo}
                  - !Sub arn:aws:s3:::${ServiceBucketName}/${ServiceBucketPath}/${GitRepo}/**
  BuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Description: !Sub ${GitRepo} to S3 to make available
      Name: !Sub ${StackPrefix}-upload-service-repo-to-s3
      ServiceRole: !Sub ${BuildIamRole.Arn}
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              commands:
                - echo Starting sync process
            build:
              commands:
                - aws s3 sync --delete . s3://${BUCKET_NAME}/${BUCKET_PATH}/
            post_build:
              commands:
                - echo Finished sync process
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/docker:1.12.1"
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: BUCKET_NAME
            Value: ${ServicesBucket}
          - Name: BUCKET_PATH
            Value: ${ServiceBucketPath}/${GitRepo}

  ServiceManagerPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: "service-manager-pipeline"
      ArtifactStore:
        Location: !Ref ArtifactBucketName
        Type: 'S3'
      RoleArn: !Ref PipelineIamRoleArn
      Stages:
        -
          Name: Source
          Actions:
            -
              Name: AppRepoSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: !Ref GitHubUser
                Repo: !Ref GitRepo
                Branch: !Ref GitBranch
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                - Name: GitHubArtifact
              RunOrder: '1'
        - Name: Deploy2S3
        # Use CodeBuild to deploy the templates to S3
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Sub ${StackPrefix}-upload-service-repo-to-s3
              InputArtifacts: [Name: 'GitHubArtifact']
              OutputArtifacts: [Name: 'BuildOutput']
              RunOrder: 20
